### ISSUE TITLE
Recipe App - Kanban Project

### ISSUE THREAD

**Issue by HansZizold** [HansZizold/recipeapp#13]
This is the link to our project:

https://github.com/HansZizold/Recipe-app/projects/1

Participants:

[Jesse Ozuma](@HeDevedUp)
[Hans Zizold](@HansZizold)

Note: we left some empty cards in case we need.

Have a nice review!!

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

## Hi team 👋, 

This milestone is complete; You have set up your kanban board correctly!  There is nothing else to say other than... it's time to start building 🚀
Congratulations! 🎉

<img src="https://media2.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/> 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
